# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  pre = "<i class='fa fa-home'></i>  "
  name = "Home"
  url = "/#2-welcome"
  weight = 10

[[main]]
  name = "FORRT"  # A link title for your page.
  url = "forrt/"  # The URL of your page.
  weight = 20  # The position of your page in the menu.
  identifier = "forrt"
  
[[main]]
  name = "About"  # A link title for your page.
  url = "/forrt#about"  # The URL of your page.
  weight = 21  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "History"  # A link title for your page.
  url = "/forrt#history"  # The URL of your page.
  weight = 22  # The position of your page in the menu.
  parent = "forrt"
  
[[main]]
  name = "Adopting FORRT"  # A link title for your page.
  url = "/forrt#adopting"  # The URL of your page.
  weight = 23  # The position of your page in the menu.
  parent = "forrt"  

[[main]]
  name = "Advocacy (click to see your talks)"  # A link title for your page.
  url = "/talk"  # The URL of your page.
  weight = 24  # The position of your page in the menu.
  parent = "forrt"
  
[[main]]
  name = "Mission"  # A link title for your page.
  url = "/forrt#mission"  # The URL of your page.
  weight = 25  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "Code of Conduct"  # A link title for your page.
  url = "/coc"  # The URL of your page.
  weight = 100  # The position of your page in the menu.


[[main]]
  name = "Education NEXUS"
  url = "/nexus"
  weight = 30
  identifier = "nexus"

[[main]]
  name = "Example of a course"
  url = "/courses/"
  weight = 31
  parent = "nexus"

[[main]]
  name = "Pedagogies"
  url = "/docs/"
  weight = 37

[[main]]
  name = "Contact Us"
  url = "/#8-contact"
  weight = 60

[[main]]
  name = "News"  # A link title for your page.
  url = "/post"  # The URL of your page.
  weight = 45  # The position of your page in the menu.