# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#   desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  pre = "<i class='fa fa-home'></i>  "
#  name = "Home"
#  url = "/#1-hero"
#  weight = 10

[[main]]
  name = "About FORRT"  # A link title for your page.
  url = ""  # The URL of your page.
  weight = 10  # The position of your page in the menu.
  identifier = "about"

[[main]]
  name = "About us"  # A link title for your page.
  url = "/about/us"  # The URL of your page.
  weight = 10  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Mission & Advocacy"  # A link title for your page.
  url = "about/mission/"  # The URL of your page.
  weight = 11  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Get Involved"  # A link title for your page.
  url = "/about/get-involved"  # The URL of your page.
  weight = 12  # The position of your page in the menu.
  parent = "about"
[[main]]
  name = "Our Community"  # A link title for your page.
  url = "/about/community"  # The URL of your page.
  weight = 13  # The position of your page in the menu.
  parent = "about"
[[main]]
  name = "Our Calendar"  # A link title for your page.
  url = "/about/get-involved/#calendar"  # The URL of your page.
  weight = 14  # The position of your page in the menu.
  parent = "about"
[[main]]
  name = "Code of Conduct"  # A link title for your page.
  url = "/coc"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "FORRT"  # A link title for your page.
  url = "/forrt/"  # The URL of your page.
  weight = 20  # The position of your page in the menu.
  identifier = "forrt"

[[main]]
  name = "Our Manuscript"  # A link title for your page.
  url = "/manuscript/"  # The URL of your page.
  weight = 22  # The position of your page in the menu.
  parent = "forrt"
[[main]]
  name = "Adopting Principled Education"  # A link title for your page.
  url = "/forrt/adopting"  # The URL of your page.
  weight = 24  # The position of your page in the menu.
  parent = "forrt"
[[main]]
  name = "FORRT's Principles"  # A link title for your page.
  url = "/forrt/principles"  # The URL of your page.
  weight = 23  # The position of your page in the menu.
  parent = "forrt"
#[[main]]
#  name = "News"  # A link title for your page.
#  url = "/forrt#featured"  # The URL of your page.
#  weight = 27  # The position of your page in the menu.
#  parent = "forrt"
# [[main]]
#   name = "Policy"  # A link title for your page.
#   url = "/forrt#policy"  # The URL of your page.
#   weight = 29  # The position of your page in the menu.
#   parent = "forrt"
# [[main]]
#   name = "Assessment"  # A link title for your page.
#   url = "/forrt/assessment/"  # The URL of your page.
#   weight = 30  # The position of your page in the menu.
#   parent = "forrt"

[[main]]
  name = "Educational NEXUS"
  url = "/nexus"
  weight = 30
  identifier = "nexus"
[[main]]
  name = "About Educational Nexus"
  url = "/nexus"
  weight = 31
  parent = "nexus"
[[main]]
  name = "Clusters"
  url = "/clusters"
  weight = 32
  parent = "nexus"
[[main]]
  name = "Resources"
  url = "/resources"
  weight = 33
  parent = "nexus"
[[main]]
  name = "Summaries"
  url = "/summaries"
  weight = 34
  parent = "nexus"
[[main]]
  name = "Self-Assessment"
  url = "/self-assessment"
  weight = 35
  parent = "nexus"
[[main]]
  name = "Educators' Corner"
  url = "/educators-corner"
  weight = 36
  parent = "nexus"
[[main]]
  name = "Towards Social Justice"
  url = "/dei"
  weight = 37
  parent = "nexus"

[[main]]
  name = "Pedagogies"
  url = "/pedagogies/"
  weight = 40
  identifier = "pedagogies"
# [[main]]
#   name = "Public"
#   url = "/pedagogies/public/"
#   weight = 41
#   parent = "pedagogies"
# [[main]]
#   name = "Undergraduate"
#   url = "/pedagogies/undergraduate/"
#   weight = 42
#   parent = "pedagogies"
# [[main]]
#   name = "Graduate"
#   url = "/pedagogies/graduate"
#   weight = 43
#   parent = "pedagogies"
