# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  pre = "<i class='fa fa-home'></i>  "
#  name = "Home"
#  url = "/#1-hero"
#  weight = 10

[[main]]
  name = "FORRT"  # A link title for your page.
  url = "/forrt/"  # The URL of your page.
  weight = 20  # The position of your page in the menu.
  identifier = "forrt"
  
[[main]]
  name = "About"  # A link title for your page.
  url = "/forrt/"  # The URL of your page.
  weight = 21  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "Adopting FORRT"  # A link title for your page.
  url = "/forrt#adopting"  # The URL of your page.
  weight = 22  # The position of your page in the menu.
  parent = "forrt"  

[[main]]
  name = "Advocacy"  # A link title for your page.
  url = "/forrt#advocacy"  # The URL of your page.
  weight = 23  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "Code of Conduct"  # A link title for your page.
  url = "/coc"  # The URL of your page.
  weight = 24  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "Get Involved"  # A link title for your page.
  url = "/forrt#get-involved"  # The URL of your page.
  weight = 25  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "Mission"  # A link title for your page.
  url = "/forrt#mission"  # The URL of your page.
  weight = 26  # The position of your page in the menu.
  parent = "forrt"

[[main]]
  name = "News"  # A link title for your page.
  url = "/forrt#featured"  # The URL of your page.
  weight = 27  # The position of your page in the menu.
  parent = "forrt"
  
[[main]]
  name = "People"  # A link title for your page.
  url = "/forrt#people"  # The URL of your page.
  weight = 28  # The position of your page in the menu.
  parent = "forrt"
  
[[main]]
  name = "Policy Making"  # A link title for your page.
  url = "/forrt#policy-making"  # The URL of your page.
  weight = 29  # The position of your page in the menu.
  parent = "forrt"
  
[[main]]
  name = "Survey"  # A link title for your page.
  url = "/forrt#survey"  # The URL of your page.
  weight = 30  # The position of your page in the menu.
  parent = "forrt"

#[[main]]
#  name = "Code of Conduct"  # A link title for your page.
#  url = "/coc"  # The URL of your page.
#  weight = 100  # The position of your page in the menu.

[[main]]
  name = "Educational NEXUS"
  url = "/courses/example/nexus/"
  weight = 30
#  identifier = "nexus"

#[[main]]
#  name = "Example of a course"
#  url = "/courses/example/"
#  weight = 31
#  parent = "nexus"

[[main]]
  name = "Pedagogies"
  url = "/courses/example/"
  weight = 37