# This workflow makes sure the website builds without error on `pushes` to the
# `main` branch and on `pull requests` that are opened to the `main` branch.
# Automatically builds and deploys to the `gh-pages` branch only when PRs
# are merged and pass all the checks.
# A cname file is added to gh-pages branch to use a custom domain.

name: Hugo test & deploy

on:
  push:
    branches:
      - master # Branch to deploy
  pull_request:
    branches:
      - master # Test PR only if master is the target branch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false # Fetch Hugo themes (true/false OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-doc.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies for resource.py
        run: |
          python3 -m pip install -r ./requirements.txt
          
      - name: Delete curated_resources
        run: |
          rm content/curated_resources/[0-9]*.md

      - name: run and make curated_resources
        run: |
          python3 content/resources/resource.py

      - name: Build
        run: hugo --gc --minify

      - name: Deploy website on push
        if: ${{ success() && github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: forrt.org
